// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA01RrodEXCJoo4jK6IG4HkCD16HdRxhcA',
    appId: '1:297650489955:web:7af14dceb94e1e187d0656',
    messagingSenderId: '297650489955',
    projectId: 'glamify-12f3b',
    authDomain: 'glamify-12f3b.firebaseapp.com',
    storageBucket: 'glamify-12f3b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvdjl1QnoTnTuQc7hwuJJ46MRQ0jdqAIU',
    appId: '1:297650489955:android:4b014dd27fed088e7d0656',
    messagingSenderId: '297650489955',
    projectId: 'glamify-12f3b',
    storageBucket: 'glamify-12f3b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhFHUYYKyZPsv3h7oNnEudbj_N2Bc7N48',
    appId: '1:297650489955:ios:2410ef3fb8126f2e7d0656',
    messagingSenderId: '297650489955',
    projectId: 'glamify-12f3b',
    storageBucket: 'glamify-12f3b.appspot.com',
    iosBundleId: 'com.example.glamify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhFHUYYKyZPsv3h7oNnEudbj_N2Bc7N48',
    appId: '1:297650489955:ios:2410ef3fb8126f2e7d0656',
    messagingSenderId: '297650489955',
    projectId: 'glamify-12f3b',
    storageBucket: 'glamify-12f3b.appspot.com',
    iosBundleId: 'com.example.glamify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA01RrodEXCJoo4jK6IG4HkCD16HdRxhcA',
    appId: '1:297650489955:web:74251fd51b7d69937d0656',
    messagingSenderId: '297650489955',
    projectId: 'glamify-12f3b',
    authDomain: 'glamify-12f3b.firebaseapp.com',
    storageBucket: 'glamify-12f3b.appspot.com',
  );
}
